// packages/vue-plugin/src/components/ContractForm.vue
<template>
  <form v-if="isDrizzleInitialized">
    <label v-for="(param, i) in displayInputs" :key="i">
      <span :style="hidden">{{ param.name }}</span>
      <input
        v-model="ethData[i]"
        :type="param.type"
        :placeholder="param.name"
      />
    </label>
    <button @click.prevent="onSubmit">Submit</button>
  </form>
</template>

<script>
import { mapGetters } from 'vuex'

const translateType = type => {
  switch (true) {
    case /^uint/.test(type):
      return 'number'
    case /^string/.test(type) || /^bytes/.test(type):
      return 'text'
    case /^bool/.test(type):
      return 'checkbox'
    default:
      return 'text'
  }
}

export default {
  name: 'ContractForm',
  props: {
    contractName: {
      type: String,
      required: true
    },
    method: {
      type: String,
      required: true
    },
    methodArgs: {
      type: Array,
      default: () => []
    },

    placeholders: {
      type: Array,
      default: () => []
    }
  },

  computed: {
    ...mapGetters('drizzle', ['drizzleInstance', 'isDrizzleInitialized']),

    abi() {
      const di = this.drizzleInstance
      return di.contracts[this.contractName].abi.find(
        item => item.name === this.method
      )
    },

    abiInputs() {
      return this.abi.inputs
    },

    displayInputs() {
      return this.abi.inputs.map((x, i) => ({
        name: this.placeholders[i] ? this.placeholders[i] : x.name,
        type: translateType(x.type)
      }))
    },

    hidden() {
      return 'display:inline-block; height: 0; width: 0; visibility: hidden;'
    },

    utils() {
      return this.drizzleInstance.web3.utils
    }
  },

  data() {
    return {
      ethData: {}
    }
  },

  methods: {
    onSubmit() {
      const convertedInputs = this.abiInputs.map((input, i) =>
        input.type === 'bytes32'
          ? (this.ethData[i] = this.utils.toHex(this.ethData[i]))
          : this.ethData[i]
      )
      const sendArgs = this.methodArgs.length
        ? [...convertedInputs, this.methodArgs]
        : convertedInputs

      this.drizzleInstance.contracts[this.contractName].methods[
        this.method
      ].cacheSend(...sendArgs)
    }
  }
}
</script>

<style></style>

// packages/react-components/src/new-context-api/ContractForm.js
import React, { Component, Fragment } from "react";
import PropTypes from "prop-types";

const translateType = type => {
  switch (true) {
    case /^uint/.test(type):
      return "number";
    case /^string/.test(type) || /^bytes/.test(type):
      return "text";
    case /^bool/.test(type):
      return "checkbox";
    default:
      return "text";
  }
};

class ContractForm extends Component {
  constructor(props) {
    super(props);

    this.handleInputChange = this.handleInputChange.bind(this);
    this.handleSubmit = this.handleSubmit.bind(this);

    this.contracts = props.drizzle.contracts;
    this.utils = props.drizzle.web3.utils;
    this.inputs = [];

    const { contract, method } = this.props;
    const initialState = {};

    // Get the contract ABI
    const abi = this.contracts[contract].abi;

    // Iterate over abi for correct function.
    for (let i = 0; i < abi.length; i++) {
      if (abi[i].name === method) {
        this.inputs = abi[i].inputs;

        for (let j = 0; j < this.inputs.length; j++) {
          initialState[this.inputs[j].name] = "";
        }

        break;
      }
    }

    this.state = initialState;
  }

  handleSubmit(event) {
    event.preventDefault();

    const { contract, method, sendArgs } = this.props;
    const convertedInputs = this.inputs.map(input => {
      if (input.type === "bytes32") {
        return this.utils.toHex(this.state[input.name]);
      }
      return this.state[input.name];
    });

    if (sendArgs) {
      return this.contracts[contract].methods[method].cacheSend(
        ...convertedInputs,
        sendArgs,
      );
    }

    return this.contracts[contract].methods[method].cacheSend(
      ...convertedInputs,
    );
  }

  handleInputChange(event) {
    const { checked, name, type } = event.target;
    const value = type === "checkbox" ? checked : event.target.value;
    this.setState({ [name]: value });
  }

  render() {
    const { labels, render } = this.props;
    const visibilityHidden = {
      visibility: "hidden",
      display: "inline-block",
      width: 0,
    };

    if (render) {
      return render({
        inputs: this.inputs,
        inputTypes: this.inputs.map(input => translateType(input.type)),
        state: this.state,
        handleInputChange: this.handleInputChange,
        handleSubmit: this.handleSubmit,
      });
    }

    return (
      <form
        className="pure-form pure-form-stacked"
        onSubmit={this.handleSubmit}
      >
        {this.inputs.map((input, index) => {
          // check if input type is struct and if so loop out struct fields as well

          const inputType = translateType(input.type);
          const inputLabel = labels ? labels[index] : input.name;

          return (
            <Fragment key={input.name}>
              <label htmlFor={input.name} style={visibilityHidden}>
                {inputLabel}
              </label>
              <input
                type={inputType}
                name={input.name}
                value={this.state[input.name]}
                placeholder={inputLabel}
                onChange={this.handleInputChange}
              />
            </Fragment>
          );
        })}
        <button
          key="submit"
          className="pure-button"
          type="button"
          onClick={this.handleSubmit}
        >
          Submit
        </button>
      </form>
    );
  }
}

ContractForm.propTypes = {
  drizzle: PropTypes.object.isRequired,
  contract: PropTypes.string.isRequired,
  method: PropTypes.string.isRequired,
  sendArgs: PropTypes.object,
  labels: PropTypes.arrayOf(PropTypes.string),
  render: PropTypes.func,
};

export default ContractForm;
